server:
  port: 8383
spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/tovarcarlosm/microservicios_2022_B.git"
          search-paths: config-data
          username: "tovarcarlosm"
          password: "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"
        bootstrap: true

  security:
    user:
      name: root
      password: pass
