server:
  port: 8383
spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/tovarcarlosm/microservicios_2022_B.git"
          searchPaths: "config-data"
          username: ${GIT_USER}
          password: ${GIT_PASS}
  security:
    user:
      name: root
      password: pass
